spring:
  datasource:
    url: jdbc:h2:file:./data/staging-db
    driver-class-name: org.h2.Driver
    username: sa
    password: staging-password
  h2:
    console:
      enabled: false
  jpa:
    show-sql: false

app:
  security:
    bearer-token: staging-secure-token-123

logging:
  level:
    com.aitrics.vital: INFO
    root: INFO